// DJ Hero
// #ID = 34823


beatName = {
    017: "Ain't No Love In The Heart Of The City / Fuzz And Them",
    038: "Insane in the Brain / The Edge",
    039: "Ice Ice Baby / U Can't Touch This",
    064: "Zulu Nation Throwdown / Get Down",
    076: "Play That Funky Music / Just to Get a Rep",
    149: "Jayou / Big Beat",
    154: "Disco Inferno / Let's Dance",
    160: "Poison / Word Up!",
    164: "Fix Up, Look Sharp / Organ Donor (Extended Overhaul)",
    169: "Intergalactic / Rapture",
    170: "Born To Roll / Mr. Big Stuff",
    171: "Insane in the Brain / Spooky",
    177: "Fix Up, Look Sharp / Genesis",
    180: "Last Night a D.J. Saved My Life / Word Up!",
    186: "Jack of Spades / Let's Dance",
    195: "Shout / Pjanoo",
    197: "Disturbia / Control",
    200: "Bustin' Loose / Time of the Season",
    208: "Disturbia / Disco Inferno",
    210: "Hollaback Girl / Give It to Me",
    213: "Satisfaction / Elements of Life",
    215: "Hollaback Girl / Feel Good Inc.",
    218: "I Heard It Through the Grapevine / Feel Good Inc.",
    220: "Poison / Intergalactic",
    226: "Ice Ice Baby / Straight Up",
    228: "Jayou / Rockit",
    237: "Lookin' At Me / Hey Mama",
    238: "I Want You Back / Semi-Charmed Life (Guitar)",
    239: "Paper Planes / Lookin' At Me",
    240: "Bring the Noise 20XX",
    251: "Beverly Hills / Fresh Rhymes and Videotape",
    253: "I Want You Back / Semi-Charmed Life",
    254: "Bustin' Loose / Bust a Move",
    255: "Boom Boom Pow / Satisfaction",
    257: "Shut 'em Down / Where It's At",
    258: "Big Beat / Lapdance",
    259: "Strange Enough ft. Karen O, ODB & Fatlip / Theme from Shaft",
    260: "Beats and Pieces",
    261: "Paper Planes / Eric B. Is President",
    262: "I Want You Back / Just to Get a Rep",
    264: "Universal Mind Control (UMC) / Jeep A** Gutter (Remix)",
    265: "Disturbia / Somebody Told Me",
    266: "Put Your Hands Up for Detroit / I Can't Stop (DP Remix)",
    267: "How Ya Like Me Now / I Like to Move It",
    270: "Somebody Told Me / Pjanoo",
    273: "Ace of Spades / Groundhog",
    275: "Disco Inferno / Last Night a D.J. Saved My Life",
    276: "Shout / Six Days (Remix ft. Mos Def)",
    278: "Groundhog",
    279: "Another One Bites the Dust / Brass Monkey",
    280: "Monkey Wrench / Sabotage",
    283: "Rockit",
    285: "Basic Tutorial 1",
    286: "Basic Tutorial 2",
    287: "Basic Tutorial 3",
    288: "Basic Tutorial 4",
    289: "Basic Tutorial 5",
    290: "Advanced Tutorial 1",
    291: "Advanced Tutorial 2",
    292: "Advanced Tutorial 4",
    295: "Technologic / Cars",
    297: "Hollaback Girl / Last Night a D.J. Saved My Life",
    298: "Da Funk / Strange Enough ft. Karen O, ODB & Fatlip",
    299: "Six Days (Remix ft. Mos Def) / Where It's At",
    302: "Here Comes My DJ / Cars",
    303: "Rockit / Lapdance",
    305: "Bittersweet Symphony / Rock the Bells",
    306: "Shout / Eric B. Is President",
    308: "Boom / Tap",
    309: "Jack of Spades / Short Circuit",
    310: "Hella Good / Television Rules the Nation",
    312: "Beats / Big Beat",
    316: "Change Clothes / All Eyez on Me",
    317: "Another One Bites the Dust / Da Funk",
    319: "Six Days (Remix ft. Mos Def) / Annie's Horn",
    321: "Lee Majors Come Again / Da Funk",
    322: "Nothing But You / I Can't Stop (DP Remix)",
    326: "Around the World / Bust a Move",
    328: "Izzo (H.O.V.A.) / I Want You Back",
    331: "Day 'n' Nite / Boom Boom Pow",
    332: "We Will Rock You / Robot Rock",
    333: "Tutti Frutti / Beats",
    336: "The Edge / Eric B. Is President",
    400: "Good Thang / Big Beat",
    402: "Poison",
    403: "Ain't No Love in the Heart of the City / How Do You Want It",
    404: "Just to Get a Rep / Shook Ones, Pt. 2",
    405: "Jukebox Hero / DJ Hero",
    406: "Jukebox Hero / DJ Hero (Guitar)",
    407: "Bring the Noise 20XX / Genesis",
    408: "My Name Is / Loser",
    409: "All Eyez on Me / Bittersweet Symphony",
    410: "Here's a Little Something For Ya / The Number Song (2009)",
    411: "Feel Good Inc. / Atomic",
    412: "Robot Rock / Al-Naafiysh (The Soul)",
    413: "Megamix 2",
    414: "Megamix 1",
    415: "Izzo (H.O.V.A.) / My Name Is",
    417: "Advanced Tutorial 5",
    418: "Advanced Tutorial 6",
    419: "Excuse Me Miss / Give It to Me",
    420: "Advanced Tutorial 3",
    675: "Fight! Smash! Win! / Intergalactic",
    681: "I Heard It Through the Grapevine / Let's Dance",
}

setlist = {
    0x00: "Quicklist/Edited Setlist/Bonus Beat",
    0x01: "Custom DJ Setlist 1",
    0x02: "Custom DJ Setlist 2",
    0x03: "Custom Guitar Setlist",
    0x04: "Learn To DJ - The Basics",
    0x05: "Learn To DJ - Advanced",
    0x06: "Scratching The Surface",
    0x07: "Party Rockin'",
    0x08: "Digging Deeper",
    0x09: "Hip Hop Rules",
    0x0a: "On The Wheels Of Steel",
    0x0b: "Thrashed & Mashed",
    0x0c: "Cut & Paste",
    0x0d: "Grandmaster Flash Presents",
    0x0e: "Jay-Z Mixtape",
    0x0f: "In The Groove",
    0x10: "Revenge Of The Boom Bap",
    0x11: "Extended Play",
    0x12: "DJ Jazzy Jeff Presents",
    0x13: "DJ Yoda Presents",
    0x14: "Daft Punk Record Bag",
    0x15: "Born To Rock",
    0x16: "Breaking Needles",
    0x17: "DJ AM Presents",
    0x18: "DJ Shadow Presents",
    0x19: "J.Period Presents",
    0x1a: "DJ Z-Trip Presents",
    0x1b: "Tearing Up Wax",
    0x1c: "Scratch Perverts Presents",
    0x1d: "The Vinyl Cut"
}

difficulty = {
    0: "Beginner",
    1: "Easy",
    2: "Medium",
    3: "Hard",
    4: "Expert"
}

beatFullComboLength = {
    017: 183,
    038: 573,
    039: 514,
    064: 523,
    076: 952,
    149: 509,
    154: 637,
    160: 523,
    164: 475,
    169: 509,
    170: 335,
    171: 373,
    177: 589,
    180: 662,
    186: 592,
    195: 428,
    197: 474,
    200: 559,
    208: 527,
    210: 583,
    213: 1161,
    215: 515,
    218: 671,
    220: 707,
    226: 559,
    228: 815,
    237: 580,
    238: 639,
    239: 717,
    240: 771,
    251: 564,
    253: 498,
    254: 779,
    255: 701,
    257: 674,
    258: 570,
    259: 644,
    260: 1375,
    261: 940,
    262: 609,
    264: 919,
    265: 673,
    266: 565,
    267: 791,
    270: 548,
    273: 668,
    275: 632,
    276: 677,
    278: 1617,
    279: 608,
    280: 437,
    283: 1496,
    295: 718,
    297: 862,
    298: 687,
    299: 549,
    302: 631,
    303: 925,
    305: 874,
    306: 639,
    308: 214,
    309: 842,
    310: 625,
    312: 826,
    316: 682,
    317: 284,
    319: 847,
    321: 807,
    322: 1048,
    326: 760,
    328: 646,
    331: 756,
    332: 540,
    333: 652,
    336: 467,
    400: 875,
    402: 391,
    403: 542,
    404: 680,
    405: 722,
    406: 722,
    407: 719,
    408: 852,
    409: 871,
    410: 761,
    411: 505,
    412: 920,
    413: 1004,
    414: 772,
    415: 785,
    419: 831,
    675: 505,
    681: 463,
}

function buildBeatId() => 100 * low4((dword_be((dword_be(0x797d64) & 0x1fffffff) + 0x356c) & 0x1fffffff) + 0x09d) +
                          10 * low4((dword_be((dword_be(0x797d64) & 0x1fffffff) + 0x356c) & 0x1fffffff) + 0x09e) +
                          low4((dword_be((dword_be(0x797d64) & 0x1fffffff) + 0x356c) & 0x1fffffff) + 0x09f)

function totalStarCount() => dword_be((dword_be((dword_be(0x797aa8) & 0x1fffffff) + 0xbc) & 0x1fffffff) + 0x1550)

function inGame() => dword_be(0x797acc) != 0
function inSong() => dword_be(0x00797d88) != 0 || 1 == 1

cheats = {
    0: "",
}

function sumOfCheats() => dword_be(0x4f4e8c) + dword_be(0x4f4ec4) + dword_be(0x4f4efc) + dword_be(0x4f4f34) + 
                          dword_be(0x4f4f6c) + dword_be(0x4f4fa4) + dword_be(0x4f4fdc) + dword_be(0x4f5014) +
                          dword_be(0x4f504c) + dword_be(0x4f5084) + dword_be(0x4f50bc) + dword_be(0x4f50f4) +
                          dword_be(0x4f512c) + dword_be(0x4f5164) + dword_be(0x4f519c) + dword_be(0x4f51d4) +
                          dword_be(0x4f52ec) + dword_be(0x4f5324) + dword_be(0x4f535c)
function isNotCheating() => sumOfCheats() == 0

function currentSongDifficulty(){
    index = dword_be((dword_be(0x797ac0) & 0x1fffffff) + 0x3b4)
    diff = dword_be((dword_be(0x797d64) & 0x1fffffff) + 0x6a4 * index + 0x08)
    return diff
}

function currentSongScore(){
    index = dword_be((dword_be(0x797ac0) & 0x1fffffff) + 0x3b4)
    score = float_be((dword_be(0x797d64) & 0x1fffffff) + 0x6a4 * index + 0x34)
    return score
}

function currentSongStars(){
    index = dword_be((dword_be(0x797ac0) & 0x1fffffff) + 0x3b4)
    stars = dword_be((dword_be(0x797d64) & 0x1fffffff) + 0x6a4 * index + 0x298)
    return stars
}

function currentSong6StarsThreshold(){
    index = dword_be((dword_be(0x797ac0) & 0x1fffffff) + 0x3b4)
    threshold = dword_be((dword_be(0x797d64) & 0x1fffffff) + 0x6a4 * index + 0x278)
    return threshold
}

function currentBeatState(){
    return dword_be((dword_be(0x797d64) & 0x1fffffff) + 0x35b0)
}

function currentStreak(){
    index = dword_be((dword_be(0x797ac0) & 0x1fffffff) + 0x3b4)
    streak = dword_be((dword_be(0x797d64) & 0x1fffffff) + 0x6a4 * index + 0x1d4)
    return streak
}

function rewindsUsed(){
    index = dword_be((dword_be(0x797ac0) & 0x1fffffff) + 0x3b4)
    rewinds = dword_be((dword_be(0x797d64) & 0x1fffffff) + 0x6a4 * index + 0x244)
    return rewinds
}

function perfectSectionsHit(){
    index = dword_be((dword_be(0x797ac0) & 0x1fffffff) + 0x3b4)
    perfects = dword_be((dword_be(0x797d64) & 0x1fffffff) + 0x6a4 * index + 0x254)
    return perfects
}

function perfectSectionsTotal(){
    index = dword_be((dword_be(0x797ac0) & 0x1fffffff) + 0x3b4)
    perfects = dword_be((dword_be(0x797d64) & 0x1fffffff) + 0x6a4 * index + 0x25c)
    return perfects
}

function euphoriasUsed(){
    index = dword_be((dword_be(0x797ac0) & 0x1fffffff) + 0x3b4)
    euphorias = dword_be((dword_be(0x797d64) & 0x1fffffff) + 0x6a4 * index + 0x24c)
    return euphorias
}


rich_presence_conditional_display(inGame() && inSong(), "{6} · {2} · {7} · Score: {8} · Total Stars: {0}/465 {1} => {3}{4}{5}", 
                                  rich_presence_value("Value", totalStarCount(), "VALUE"),
                                  rich_presence_lookup("Cheats", sumOfCheats(), cheats, fallback=" - Using Cheats"),
                                  rich_presence_lookup("Beat", buildBeatId(), beatName, fallback="Unknown Beat"),
                                  rich_presence_value("ASCIIChar", low4((dword_be((dword_be(0x797d64) & 0x1fffffff) + 0x356c) & 0x1fffffff) + 0x09d)),
                                  rich_presence_value("ASCIIChar", low4((dword_be((dword_be(0x797d64) & 0x1fffffff) + 0x356c) & 0x1fffffff) + 0x09e)),
                                  rich_presence_value("ASCIIChar", low4((dword_be((dword_be(0x797d64) & 0x1fffffff) + 0x356c) & 0x1fffffff) + 0x09f)),
                                  rich_presence_lookup("Setlist", dword_be((dword_be(0x797ac0) & 0x1fffffff) + 0x3b0), setlist),
                                  rich_presence_lookup("Difficulty", currentSongDifficulty(), difficulty),
                                  rich_presence_value("Score", currentSongScore(), "SCORE")
)

rich_presence_conditional_display(inGame(), "In the Hub · Total Stars: {0}/465 {1}", 
                                  rich_presence_value("Value", totalStarCount(), "VALUE"),
                                  rich_presence_lookup("CHEATS", sumOfCheats(), cheats, fallback=" - Using Cheats")
)

rich_presence_display("Playing DJ Hero")

basicTutorialsOffsets = [0x11e0, 0x11f0, 0x1200, 0x1210, 0x1220]
advancedTutorialsOffsets = [0x1230, 0x1240, 0x05d0, 0x1250, 0x0640, 0x05c0]

function masteringTutorials(offsets){
    prev = always_false()
    mem = always_true()
    for offset in offsets{
        prev = prev || prev(dword_be((dword_be((dword_be(0x797aa8) & 0x1fffffff) + 0xbc) & 0x1fffffff) + offset)) != 0x180
        mem = mem && dword_be((dword_be((dword_be(0x797aa8) & 0x1fffffff) + 0xbc) & 0x1fffffff) + offset) == 0x180
    }
    return isNotCheating() && inGame() && prev && mem
}

achievement(title="Mastering the Basics", points=1,
            description="Master all Basic Tutorial entries",
            trigger=masteringTutorials(basicTutorialsOffsets)
)

achievement(title="Advanced Degree", points=2,
            description="Master all Advanced Tutorial entries",
            trigger=masteringTutorials(advancedTutorialsOffsets)
)

progressionData = [
    ["Scratching the Surface", [0x0120, 0x0320, 0x0ab0], 3, ""],
    ["Party Rockin'", [0x0ac0, 0x0c40, 0x0a10, 0x00c0], 4, ""],
    ["Digging Deeper", [0x02f0, 0x0180, 0x0160, 0x01e0], 4, ""],
    ["Hip Hop Rules", [0x01f0, 0x0960, 0x0280, 0x0a50], 4, ""],
    ["On the Wheels of Steel", [0x0db0, 0x0d30, 0x10b0, 0x0200], 4, ""], 
    ["Trashed and Mashed", [0x00d0, 0x02c0, 0x04d0, 0x02e0, 0x02b0], 5, ""], 
    ["Cut and Paste", [0x0080, 0x0220, 0x0130, 0x10f0], 4, ""],
    ["Grandmaster Flash Presents", [0x1300, 0x12f0], 2, "non-bonus "],
    ["Jay-Z Mixtape", [0x0020, 0x0390, 0x0300, 0x0030], 4, ""],
    ["In the Groove", [0x0d80, 0x10c0, 0x01c0, 0x0b20], 4, ""],
    ["Revenge of the Boom Bap", [0x0b50, 0x1020, 0x0370, 0x0040], 4, ""],   
    ["Extended Play", [0x0ee0, 0x0e30, 0x0290, 0x0070], 4, ""],
    ["DJ Jazzy Jeff Presents", [0x00e0, 0x0100], 2, "non-bonus "],
    ["DJ Yoda Presents", [0x1070, 0x14e0], 2, "non-bonus "],
    ["Daft Punk Record Bag", [0x00a0, 0x0060, 0x1370, 0x0340, 0x0330, 0x0170, 0x03b0], 10, "non-bonus "],
    ["Born to Rock", [0x00f0, 0x0140, 0x0230, 0x0190, 0x0f10], 5, ""],
    ["Breaking Needles", [0x0360, 0x0f00, 0x0350, 0x00b0], 4, ""],
    ["DJ AM Presents", [0x12a0, 0x0dd0], 2, "non-bonus "],  
    ["DJ Shadow Presents", [0x0bb0, 0x0c90, 0x01d0], 3, "non-bonus "],
    ["J.Period Presents", [0x01a0, 0x03c0], 2, ""],
    ["DJ Z-Trip Presents", [0x01b0, 0x0110], 2, "non-bonus "],
    ["Tearing up Wax", [0x0260, 0x0210, 0x0240, 0x0e50], 4, ""],
    ["Scratch Perverts Presents", [0x0050, 0x03a0, 0x0090, 0x1090, 0x1170], 5, ""],
    ["The Vinyl Cut", [0x0240, 0x0350, 0x1170, 0x0d60], 1, ""]
]
 
// 5 of those is 0xa0000000, 3 is 0x60000000, 1 is 0x20000000
function mediumStars(baseOffset) => dword_be((dword_be((dword_be(0x797aa8) & 0x1fffffff) + 0xbc) & 0x1fffffff) + baseOffset + 4) & 0xe0000000

// 5 of those is 0xa0, 3 is 0x60, 1 is 0x20
function hardStars(baseOffset) => dword_be((dword_be((dword_be(0x797aa8) & 0x1fffffff) + 0xbc) & 0x1fffffff) + baseOffset + 4) & 0xe0

// 5 of those is 0x14, 3 is 0xc, 1 is 0x4
function expertStars(baseOffset) => dword_be((dword_be((dword_be(0x797aa8) & 0x1fffffff) + 0xbc) & 0x1fffffff) + baseOffset + 4) & 0x1c

function progressionAchievement(offsets){
    prev = always_false()
    mem = always_true()
    combo = always_true()
    for offset in offsets{
        prev = prev || (prev(mediumStars(offset)) < 0x20000000 && mediumStars(offset) >= 0x20000000 || prev(hardStars(offset)) < 0x20 && hardStars(offset) >= 0x20 || prev(expertStars(offset)) < 0x4 && expertStars(offset) >= 0x4)
        mem = mem && (mediumStars(offset) >= 0x20000000 || hardStars(offset) >= 0x20 || expertStars(offset) >= 0x4)
    }
    return isNotCheating() && inGame() && prev && mem 
}

for progression in progressionData{
    achievement(title=progression[0], points=progression[2], type="progression",
                description="Earn at least 1 Star in all " + progression[3] + "Mixes in " + progression[0] + " on Medium difficulty or higher",
                trigger=progressionAchievement(progression[1])
    )
}

function unlockBonusBeat(offset)
{
   return isNotCheating() && inGame() && prev(dword_be((dword_be((dword_be(0x797aa8) & 0x1fffffff) + 0xbc) & 0x1fffffff) + offset)) / 0x80000000 == 0 && dword_be((dword_be((dword_be(0x797aa8) & 0x1fffffff) + 0xbc) & 0x1fffffff) + offset) / 0x80000000 == 1  
}
achievement(title="Mashed in a Flash", points=5,
            description="Unlock the bonus track in Grandmaster Flash Presents",
            trigger=unlockBonusBeat(0x1350)
)

achievement(title="Up for Some Extra Jazz", points=5,
            description="Unlock the bonus track in DJ Jazzy Jeff Presents",
            trigger=unlockBonusBeat(0x0270)
)

achievement(title="Do or Do Not, There Is One More to Try", points=5,
            description="Unlock the bonus track in DJ Yoda Presents",
            trigger=unlockBonusBeat(0x02d0)
)

achievement(title="Bottomless Bag", points=5,
            description="Unlock the bonus track in Daft Punk Record Bag",
            trigger=unlockBonusBeat(0x02a0)
)

achievement(title="I AM Ready for More", points=5,
            description="Unlock the bonus track in DJ AM Presents",
            trigger=unlockBonusBeat(0x0310)
)

achievement(title="One More Sonic Treat", points=5,
            description="Unlock the bonus track in DJ Shadow Presents",
            trigger=unlockBonusBeat(0x1420)
)

achievement(title="A Through Z... And Then Some", points=5,
            description="Unlock the bonus track in DJ Z-Trip Presents",
            trigger=unlockBonusBeat(0x0150)
)

achievement(title="A Final Treat Before You Go", points=3,
            description="Unlock the bonus track in The Vinyl Cut",
            trigger=unlockBonusBeat(0x0250)
)

achievement(title="Back and Forth with the Flow", points=10,
            description="On Expert difficulty, perform three Rewinds within the same Note Streak on any Beat",
            trigger=isNotCheating() && inGame() && currentSongDifficulty() == 4 && currentBeatState() == 0x9 && never(currentStreak() == 0) && tally(3, prev(rewindsUsed()) < rewindsUsed())
)

achievement(title="Stoicism", points=10,
            description="On Expert difficulty, earn 5 Stars on any Beat without using Euphoria and ending with a full Euphoria Meter",
            trigger=isNotCheating() && inGame() && currentSongDifficulty() == 4 && perfectSectionsHit() >= 3 && euphoriasUsed() == 0 && currentSongStars() == 5 && prev(currentBeatState()) == 0x09 && (currentBeatState() == 0x0f || currentBeatState() == 0x13)
)

achievement(title="Localized Perfection", points=5,
            description="On Expert difficulty, hit all Perfect Sections on any Beat",
            trigger=isNotCheating() && inGame() && currentSongDifficulty() == 4 && currentBeatState() == 0x9 && perfectSectionsHit() == perfectSectionsTotal() && prev(perfectSectionsHit()) < perfectSectionsHit()
)

achievement(title="6-Stars Victory", points=10,
            description="On Expert difficulty, reach the hidden 6-Stars threshold on any Beat",
            trigger=isNotCheating() && inGame() && currentSongDifficulty() == 4 && currentSongScore() >= currentSong6StarsThreshold() && prev(currentBeatState()) == 0x09 && (currentBeatState() == 0x0f || currentBeatState() == 0x13)
)

fullsetChallenges = [
    ["Joseph Saddler", "Grandmaster Flash Presents", [303, 302, 308], 15, 0x0d],
    ["Jeffrey Allen Townes", "DJ Jazzy Jeff Presents", [305, 306, 038], 15, 0x12],
    ["Thomas Bangalter & Guy-Manuel de Homem-Christo", "Daft Punk Record Bag", [332, 298, 310, 309, 326, 295, 414, 413], 40, 0x14],
    ["Adam Goldstein", "DJ AM Presents", [297, 220, 402], 15, 0x17],
    ["Joshua Paul Davis", "DJ Shadow Presents", [186, 200, 410, 321], 20, 0x18],
    ["Zach Sciacca", "DJ Z-Trip Presents", [407, 279, 405], 15, 0x1a],    
]

function fullsetAchievement(setlistId, idList)
{
    checkpoints = always_true()
    beat_index = dword_be((dword_be(0x797ac0) & 0x1fffffff) + 0x3b4)
    for loop_index in range(0, length(idList) - 2)
    {        
        checkpoints = checkpoints && once(beat_index == loop_index && buildBeatId() == idList[loop_index] && currentSongDifficulty() == 4 && currentSongStars() == 5 && prev(currentBeatState()) == 0x09 && currentBeatState() == 0x0f)
    }
    final_index = length(idList) - 1
    checkpoints = checkpoints && beat_index == final_index && buildBeatId() == idList[final_index] && currentSongDifficulty() == 4 && currentSongStars() == 5 && prev(currentBeatState()) == 0x09 && currentBeatState() == 0x13
    return isNotCheating() && inGame() && never(currentBeatState() == 0x01) && dword_be((dword_be(0x797ac0) & 0x1fffffff) + 0x3b0) == setlistId && checkpoints
}

for fullsetChallenge in fullsetChallenges{
    achievement(title=fullsetChallenge[0], points=25,
                description="On Expert difficulty, earn all " + fullsetChallenge[3] + " Stars on the entire " + fullsetChallenge[1] + " set in one go while keeping the default Beats order",
                trigger=fullsetAchievement(fullsetChallenge[4], fullsetChallenge[2])
    )
}

// [Id, Title, Full Combo Length, Five 5 Expert Achievement Title]
challengeData = [
    [17, "Ain't No Love In The Heart Of The City / Fuzz And Them", 183, "Ain't No Fuzz"],
    [38, "Insane in the Brain / The Edge", 573, "The Brain Edge"],
    [39, "Ice Ice Baby / U Can't Touch This", 514, "Ice Touch"],
    [64, "Zulu Nation Throwdown / Get Down", 523, "Throwdown Down"],
    [76, "Play That Funky Music / Just to Get a Rep", 952, "Just to Get Funky Music"],
    [149, "Jayou / Big Beat", 509, "The Big Jayou"],
    [154, "Disco Inferno / Let's Dance", 637, "Inferno Dance"],
    [160, "Poison / Word Up!", 523, "Poison Word"],
    [164, "Fix Up, Look Sharp / Organ Donor (Extended Overhaul)", 475, "You Look Sharp, No Wonder the Sound Has So Much Body"],
    [169, "Intergalactic / Rapture", 509, "Intergalactic Rapture"],
    [170, "Born To Roll / Mr. Big Stuff", 335, "Mr. Big Roll"],
    [171, "Insane in the Brain / Spooky", 373, "Spooky Brain"],
    [177, "Fix Up, Look Sharp / Genesis", 589, "Hear the Bang, See the Genesis"],
    [180, "Last Night a D.J. Saved My Life / Word Up!", 662, "Last Word"],
    [186, "Jack of Spades / Let's Dance", 592, "Jack of Spades Under the Moonlight"],
    [195, "Shout / Pjanoo", 428, "You Shouldn't Have to Sell Your Pjanoo"],
    [197, "Disturbia / Control", 474, "Your Mind's In Control"],
    [200, "Bustin' Loose / Time of the Season", 559, "Bustin' the Season"],
    [208, "Disturbia / Disco Inferno", 527, "Disturbed Disco"],
    [210, "Hollaback Girl / Give It to Me", 583, "Hollaback Baby"],
    [213, "Satisfaction / Elements of Life", 1161, "Satisfying Elements"],
    [215, "Hollaback Girl / Feel Good Inc.", 515, "Feel Good Girl"],
    [218, "I Heard It Through the Grapevine / Feel Good Inc.", 671, "Grapevine Inc."],
    [220, "Poison / Intergalactic", 707, "Intergalactic Poison"],
    [226, "Ice Ice Baby / Straight Up", 559, "Straight Up on the Ice"],
    [228, "Jayou / Rockit", 815, "We're Known to Rockit"],
    [237, "Lookin' At Me / Hey Mama", 580, "Lookin' at Mama"],
    [238, "I Want You Back / Semi-Charmed Life (Guitar)", 639, "I Want Life and My Guitar Back"],
    [239, "Paper Planes / Lookin' At Me", 717, "Lookin' at Paper Planes"],
    [240, "Bring the Noise 20XX", 771, "Bring the Noise 20XX on the Rocks"],
    [251, "Beverly Hills / Fresh Rhymes and Videotape", 564, "Beverly Hills Videotape"],
    [253, "I Want You Back / Semi-Charmed Life", 498, "I Want Life Back"],
    [254, "Bustin' Loose / Bust a Move", 779, "Bustin' a Move"],
    [255, "Boom Boom Pow / Satisfaction", 701, "Gotta Get Satisfaction"],
    [257, "Shut 'em Down / Where It's At", 674, "Down Where It's At"],
    [258, "Big Beat / Lapdance", 570, "Big Lapdance"],
    [259, "Strange Enough ft. Karen O, ODB & Fatlip / Theme from Shaft", 644, "Strange Shaft"],
    [260, "Beats and Pieces", 1375, "Beats and Pieces on the Rocks"],
    [261, "Paper Planes / Eric B. Is President", 940, "Presidential Papers"],
    [262, "I Want You Back / Just to Get a Rep", 609, "I Just Want to Get a Rep"],
    [264, "Universal Mind Control (UMC) / Jeep A** Gutter (Remix)", 919, "Universal A** Control"],
    [265, "Disturbia / Somebody Told Me", 673, "Somebody Disturbed Me"],
    [266, "Put Your Hands Up for Detroit / I Can't Stop (DP Remix)", 565, "Detroit Can't Stop"],
    [267, "How Ya Like Me Now / I Like to Move It", 791, "How Ya Like to Move"],
    [270, "Somebody Told Me / Pjanoo", 548, "Somebody Told Me You Play The Pjanoo"],
    [273, "Ace of Spades / Groundhog", 668, "Groundhog Eyes Watching You"],
    [275, "Disco Inferno / Last Night a D.J. Saved My Life", 632, "Last Night a DJ Saved Disco"],
    [276, "Shout / Six Days (Remix ft. Mos Def)", 677, "Shouting Days"],
    [278, "Groundhog", 1617, "Groundhog on the Rocks"],
    [279, "Another One Bites the Dust / Brass Monkey", 608, "Another One Bites the Brass"],
    [280, "Monkey Wrench / Sabotage", 437, "The Right Tool to Sabotage"],
    [283, "Rockit", 1496, "Rockit on the Rocks"],
    [295, "Technologic / Cars", 718, "Technologic Cars"],
    [297, "Hollaback Girl / Last Night a D.J. Saved My Life", 862, "Last Night a DJ Saved My Girl"],
    [298, "Da Funk / Strange Enough ft. Karen O, ODB & Fatlip", 687, "Strange Funk"],
    [299, "Six Days (Remix ft. Mos Def) / Where It's At", 549, "It's At Six"],
    [302, "Here Comes My DJ / Cars", 631, "Here Comes My Car"],
    [303, "Rockit / Lapdance", 925, "Lapdance Rock"],
    [305, "Bittersweet Symphony / Rock the Bells", 874, "Symphonic Bells"],
    [306, "Shout / Eric B. Is President", 639, "Presidential Shout"],
    [308, "Boom / Tap", 214, "Boom Tap"],
    [309, "Jack of Spades / Short Circuit", 842, "Short Spades"],
    [310, "Hella Good / Television Rules the Nation", 625, "Good Rules the Nation"],
    [312, "Beats / Big Beat", 826, "The Big Beats"],
    [316, "Change Clothes / All Eyez on Me", 682, "All Clothes on Me"],
    [317, "Another One Bites the Dust / Da Funk", 284, "Another One Bites Da Funk"],
    [319, "Six Days (Remix ft. Mos Def) / Annie's Horn", 847, "Annie's Days"],
    [321, "Lee Majors Come Again / Da Funk", 807, "Funk Comes Again"],
    [322, "Nothing But You / I Can't Stop (DP Remix)", 1048, "I Can't Stop You"],
    [326, "Around the World / Bust a Move", 760, "Bust the World"],
    [328, "Izzo (H.O.V.A.) / I Want You Back", 646, "I Want Jehovah"],
    [331, "Day 'n' Nite / Boom Boom Pow", 756, "Boom Boom Day"],
    [332, "We Will Rock You / Robot Rock", 540, "Robot Will Rock You"],
    [333, "Tutti Frutti / Beats", 652, "Beatsi Frutti"],
    [336, "The Edge / Eric B. Is President", 467, "President on the Edge"],
    [400, "Good Thang / Big Beat", 875, "The Good Beat"],
    [402, "Poison", 391, "Poison on the Rocks"],
    [403, "Ain't No Love in the Heart of the City / How Do You Want It", 542, "How Do U Want Love?"],
    [404, "Just to Get a Rep / Shook Ones, Pt. 2", 680, "Got a Rep as the Infamous"],
    [405, "Jukebox Hero / DJ Hero", 722, "Couple of Heroes"],
    [406, "Jukebox Hero / DJ Hero (Guitar)", 722, "Couple of Heroes with a Guitar"],
    [407, "Bring the Noise 20XX / Genesis", 719, "Bring the Genesis"],
    [408, "My Name Is / Loser", 852, "My Name Is NOT Loser"],
    [409, "All Eyez on Me / Bittersweet Symphony", 871, "All Eyez on the Symphony"],
    [410, "Here's a Little Something For Ya / The Number Song (2009)", 761, "Here's The Number Song for Ya"],
    [411, "Feel Good Inc. / Atomic", 505, "Feel Atomic"],
    [412, "Robot Rock / Al-Naafiysh (The Soul)", 920, "The Robot Soul"],
    [413, "Megamix 2", 1004, "Daft Punk Megamix 1"],
    [414, "Megamix 1", 772, "Daft Punk Megamix 2"],
    [415, "Izzo (H.O.V.A.) / My Name Is", 785, "My Name is Jehovah"],
    [419, "Excuse Me Miss / Give It to Me", 831, "Git It to Me Miss"],
    [675, "Fight! Smash! Win! / Intergalactic", 505, "Intergalactic Win!"],
    [681, "I Heard It Through the Grapevine / Let's Dance", 463, "Let's Dance Through the Grapevine"],    
]

for challengeDataLine in challengeData{
    achievement(title=challengeDataLine[3], points=10,
                description="Earn 5 Stars on " + challengeDataLine[1] + " on Expert difficulty",
                trigger=isNotCheating() && inGame() && buildBeatId() == challengeDataLine[0] && currentSongDifficulty() == 4 && currentSongStars() == 5 && prev(currentBeatState()) == 0x09 && (currentBeatState() == 0x0f || currentBeatState() == 0x13)
    )
}
