// DJ Hero
// #ID = 34823


beatName = {
    328: "Izzo (H.O.V.A.) / I Want You Back",
    415: "Izzo (H.O.V.A.) / My Name Is",
    331: "Day 'n' Nite / Boom Boom Pow",
    004: "Paper Planes / Eric B. Is President",
    298: "Da Funk / Strange Enough ft. Karen O, ODB & Fatlip",
    254: "Bustin' Loose / Bust a Move",
    169: "Intergalactic / Rapture",
    008: "Robot Rock / Al-Naafiysh (The Soul)",
    332: "We Will Rock You / Robot Rock",
    275: "Disco Inferno / Last Night a D.J. Saved My Life",
    411: "Feel Good Inc. / Atomic",
    012: "Big Beat / Lapdance",
    305: "Bittersweet Symphony / Rock the Bells",
    014: "Fight! Smash! Win! / Intergalactic",
    306: "Shout / Eric B. Is President",
    279: "Another One Bites the Dust / Brass Monkey",
    017: "Ain't No Love In The Heart Of The City / Fuzz And Them",
    154: "Disco Inferno / Let's Dance",
    019: "Ace of Spades / Groundhog",
    020: "Jukebox Hero / DJ Hero (Standard)",
    197: "Disturbia / Control",
    295: "Technologic / Cars",
    255: "Boom Boom Pow / Satisfaction",
    024: "Jukebox Hero / DJ Hero (Guitar)",
    404: "Just to Get a Rep / Shook Ones, Pt. 2",
    407: "Bring the Noise 20XX / Genesis",
    208: "Disturbia / Disco Inferno",
    028: "Here's a Little Something For Ya / The Number Song",
    403: "Ain't No Love in the Heart of the City / How Do You Want It",
    064: "Zulu Nation Throwdown / Get Down",
    408: "My Name Is / Loser",
    032: "Nothing but You / I Can't Stop (DP Remix)",
    299: "Six Days (Remix ft. Mos Def) / Where It's At",
    034: "Monkey Wrench / Sabotage",
    035: "Six Days (Remix ft. Mos Def) / Annie's Horn",
    036: "Rockit",
    037: "Strange Enough ft. Karen O, ODB & Fatlip / Theme from Shaft",
    038: "Insane in the Brain / The Edge",
    039: "Ice Ice Baby / U Can't Touch This",
    336: "The Edge / Eric B. Is President",
    413: "Megamix 2",
    042: "Beverly Hills / Fresh Rhymes and Videotape",
    043: "I Want You Back / Semi-Charmed Life (Guitar)",
    312: "Beats / Big Beat",
    045: "Disturbia / Somebody Told Me",
    253: "I Want You Back / Semi-Charmed Life",
    316: "Change Clothes / All Eyez on Me",
    402: "Poison",
    317: "Another One Bites the Dust / Da Funk",
    326: "Around the World / Bust a Move",
    309: "Jack of Spades / Short Circuit",
    681: "I Heard It Through the Grapevine / Let's Dance",
    409: "All Eyez on Me / Bittersweet Symphony",
    276: "Shout / Six Days (Remix ft. Mos Def)",
    419: "Excuse Me Miss / Give It to Me",
    057: "Beats and Pieces",
    414: "Megamix 1",
    400: "Good Thang / Big Beat",
    076: "Play That Funky Music / Just to Get a Rep",
    149: "Jayou / Big Beat",
    160: "Poison / Word Up!",
    164: "Fix Up, Look Sharp / Organ Donor (Extended Overhaul)",
    170: "Born To Roll / Mr. Big Stuff",
    171: "Insane in the Brain / Spooky",
    177: "Fix Up, Look Sharp / Genesis",
    180: "Last Night a D.J. Saved My Life / Word Up!",
    186: "Jack of Spades / Let's Dance",
    195: "Shout / Pjanoo",
    200: "Bustin' Loose / Time of the Season",
    210: "Hollaback Girl / Give It to Me",
    213: "Satisfaction / Elements of Life",
    215: "Hollaback Girl / Feel Good Inc.",
    218: "I Heard It Through the Grapevine / Feel Good Inc.",
    220: "Poison / Intergalactic",
    226: "Ice Ice Baby / Straight Up",
    228: "Jayou / Rockit",
    237: "Lookin' At Me / Hey Mama",
    239: "Paper Planes / Lookin' At Me",
    240: "Bring the Noise 20XX",
    257: "Shut 'em Down / Where It's At",
    262: "I Want You Back / Just to Get a Rep",
    264: "Universal Mind Control (UMC) / Jeep A** Gutter (Remix)",
    266: "Put Your Hands Up for Detroit / I Can't Stop (DP Remix)",
    267: "How Ya Like Me Now / I Like to Move It",
    270: "Somebody Told Me / Pjanoo",
    278: "Groundhog",
    297: "Hollaback Girl / Last Night a D.J. Saved My Life",
    302: "Here Comes My DJ / Cars",
    303: "Rockit / Lapdance",
    308: "Boom / Tap",
    310: "Hella Good / Television Rules the Nation",
    321: "Lee Majors Come Again / Da Funk",
    333: "Tutti Frutti / Beats"
}

setlist = {
    0x00: "Quicklist/Edited Setlist/Bonus Beat",
    0x01: "Custom DJ Setlist 1",
    0x02: "Custom DJ Setlist 2",
    0x03: "Custom Guitar Setlist",
    0x04: "Learn To DJ - The Basics",
    0x05: "Learn To DJ - Advanced",
    0x06: "Scratching The Surface",
    0x07: "Party Rockin'",
    0x08: "Digging Deeper",
    0x09: "Hip Hop Rules",
    0x0a: "On The Wheels Of Steel",
    0x0b: "Thrashed & Mashed",
    0x0c: "Cut & Paste",
    0x0d: "Grandmaster Flash Presents",
    0x0e: "Jay-Z Mixtape",
    0x0f: "In The Groove",
    0x10: "Revenge Of The Boom Bap",
    0x11: "Extended Play",
    0x12: "DJ Jazzy Jeff Presents",
    0x13: "DJ Yoda Presents",
    0x14: "Daft Punk Record Bag",
    0x15: "Born To Rock",
    0x16: "Breaking Needles",
    0x17: "DJ AM Presents",
    0x18: "DJ Shadow Presents",
    0x19: "J.Period Presents",
    0x1a: "DJ Z-Trip Presents",
    0x1b: "Tearing Up Wax",
    0x1c: "Scratch Perverts Presents",
    0x1d: "The Vinyl Cut"
}

difficulty = {
    0: "Beginner",
    1: "Easy",
    2: "Medium",
    3: "Hard",
    4: "Expert"
}

beatFullComboLength = {
    170: 335,
    017: 183,
    317: 284,
    197: 474,
    064: 523,
    039: 514,
    253: 498,
    149: 509,
    171: 373,
    195: 428,
    218: 671,
    308: 214,
    328: 646,
    254: 779,
    169: 509,
    332: 540,
    411: 505,
    255: 701,
    208: 527,
    038: 573,
    402: 391,
    276: 677,
    160: 523,
    164: 475,
    177: 589,
    200: 559,
    210: 583,
    215: 515,
    226: 559,
    257: 674,
    266: 565,
    302: 631,
    303: 925,
    415: 785,
    331: 756,
    298: 687,
    275: 632,
    305: 874,
    306: 639,
    279: 608,
    154: 637,
    295: 718,
    404: 680,
    407: 719,
    403: 542,
    408: 852,
    299: 549,
    336: 467,
    413: 1004,
    312: 826,
    316: 682,
    326: 760,
    309: 842,
    681: 463,
    409: 871,
    419: 831,
    414: 772,
    400: 875,
    180: 662,
    186: 592,
    220: 707,
    237: 580,
    239: 717,
    262: 609,
    267: 791,
    270: 548,
    297: 862,
    310: 625,
    333: 652,
    // xxx: ,
}

function buildBeatId() => 100 * low4((dword_be((dword_be(0x797d64) & 0x1fffffff) + 0x356c) & 0x1fffffff) + 0x09d) +
                          10 * low4((dword_be((dword_be(0x797d64) & 0x1fffffff) + 0x356c) & 0x1fffffff) + 0x09e) +
                          low4((dword_be((dword_be(0x797d64) & 0x1fffffff) + 0x356c) & 0x1fffffff) + 0x09f)

function totalStarCount() => dword_be((dword_be((dword_be(0x797aa8) & 0x1fffffff) + 0xbc) & 0x1fffffff) + 0x1550)

function inGame() => dword_be(0x797acc) != 0
function inSong() => dword_be(0x00797d88) != 0

cheats = {
    0: "",
}

function sumOfCheats() => dword_be(0x4f4e8c) + dword_be(0x4f4ec4) + dword_be(0x4f4efc) + dword_be(0x4f4f34) + 
                          dword_be(0x4f4f6c) + dword_be(0x4f4fa4) + dword_be(0x4f4fdc) + dword_be(0x4f5014) +
                          dword_be(0x4f504c) + dword_be(0x4f5084) + dword_be(0x4f50bc) + dword_be(0x4f50f4) +
                          dword_be(0x4f512c) + dword_be(0x4f5164) + dword_be(0x4f519c) + dword_be(0x4f51d4) +
                          dword_be(0x4f52ec) + dword_be(0x4f5324) + dword_be(0x4f535c)
function isNotCheating() => sumOfCheats() == 0

function currentSongDifficulty(){
    index = dword_be((dword_be(0x797ac0) & 0x1fffffff) + 0x3b4)
    diff = dword_be((dword_be(0x797d64) & 0x1fffffff) + 0x6a4 * index + 0x08)
    return diff
}

function currentSongScore(){
    index = dword_be((dword_be(0x797ac0) & 0x1fffffff) + 0x3b4)
    score = float_be((dword_be(0x797d64) & 0x1fffffff) + 0x6a4 * index + 0x34)
    return score
}

rich_presence_conditional_display(inGame() && inSong(), "{6} - {2} - {7} - Score: {8} - Total Stars: {0}/465 {1} => {3}{4}{5}", 
                                  rich_presence_value("Value", totalStarCount(), "VALUE"),
                                  rich_presence_lookup("Cheats", sumOfCheats(), cheats, fallback=" - Using Cheats"),
                                  rich_presence_lookup("Beat", buildBeatId(), beatName, fallback="Unknown Beat"),
                                  rich_presence_value("ASCIIChar", low4((dword_be((dword_be(0x797d64) & 0x1fffffff) + 0x356c) & 0x1fffffff) + 0x09d)),
                                  rich_presence_value("ASCIIChar", low4((dword_be((dword_be(0x797d64) & 0x1fffffff) + 0x356c) & 0x1fffffff) + 0x09e)),
                                  rich_presence_value("ASCIIChar", low4((dword_be((dword_be(0x797d64) & 0x1fffffff) + 0x356c) & 0x1fffffff) + 0x09f)),
                                  rich_presence_lookup("Setlist", dword_be((dword_be(0x797ac0) & 0x1fffffff) + 0x3b0), setlist),
                                  rich_presence_lookup("Difficulty", currentSongDifficulty(), difficulty),
                                  rich_presence_value("Score", currentSongScore(), "SCORE")
)

rich_presence_conditional_display(inGame(), "In the Hub - Total Stars: {0}/465 {1}", 
                                  rich_presence_value("Value", totalStarCount(), "VALUE"),
                                  rich_presence_lookup("CHEATS", sumOfCheats(), cheats, fallback=" - Using Cheats")
)

rich_presence_display("Playing DJ Hero")

basicTutorialsOffsets = [0x11e0, 0x11f0, 0x1200, 0x1210, 0x1220]
advancedTutorialsOffsets = [0x1230, 0x1240, 0x05d0, 0x1250, 0x0640, 0x05c0]

function masteringTutorials(offsets){
    prev = always_false()
    mem = always_true()
    for offset in offsets{
        prev = prev || prev(dword_be((dword_be((dword_be(0x797aa8) & 0x1fffffff) + 0xbc) & 0x1fffffff) + offset)) != 0x180
        mem = mem && dword_be((dword_be((dword_be(0x797aa8) & 0x1fffffff) + 0xbc) & 0x1fffffff) + offset) == 0x180
    }
    return isNotCheating() && inGame() && prev && mem
}

achievement(title="Mastering the Basics", points=1,
            description="Master all Basic Tutorial entries",
            trigger=masteringTutorials(basicTutorialsOffsets)
)

achievement(title="Advanced Degree", points=2,
            description="Master all Advanced Tutorial entries",
            trigger=masteringTutorials(advancedTutorialsOffsets)
)

progressionData = [
    ["Scratching the Surface", [0x0120, 0x0320, 0x0ab0], 3, ""],
    ["Party Rockin'", [0x0ac0, 0x0c40, 0x0a10, 0x00c0], 4, ""],
    ["Digging Deeper", [0x02f0, 0x0180, 0x0160, 0x01e0], 4, ""],
    ["Hip Hop Rules", [0x01f0, 0x0960, 0x0280, 0x0a50], 4, ""],
    ["On the Wheels of Steel", [0x0db0, 0x0d30, 0x10b0, 0x0200], 4, ""], 
    ["Trashed and Mashed", [0x00d0, 0x02c0, 0x04d0, 0x02e0, 0x02b0], 5, ""], 
    ["Cut and Paste", [0x0080, 0x0220, 0x0130, 0x10f0], 4, ""],
    ["Grandmaster Flash Presents", [0x1300, 0x12f0], 2, "non-bonus "],
    ["Jay-Z Mixtape", [0x0020, 0x0390, 0x0300, 0x0030], 4, ""],
    ["In the Groove", [0x0d80, 0x10c0, 0x01c0, 0x0b20], 4, ""],
    ["Revenge of the Boom Bap", [0x0b50, 0x1020, 0x0370, 0x0040], 4, ""],   
    ["Extended Play", [0x0ee0, 0x0e30, 0x0290, 0x0070], 4, ""],
    ["DJ Jazzy Jeff Presents", [0x00e0, 0x0100], 2, "non-bonus "],
    ["DJ Yoda Presents", [0x1070, 0x14e0], 2, "non-bonus "],
    ["Daft Punk Record Bag", [0x00a0, 0x0060, 0x1370, 0x0340, 0x0330, 0x0170, 0x03b0], 10, "non-bonus "],
    ["Born to Rock", [0x00f0, 0x0140, 0x0230, 0x0190, 0x0f10], 5, ""],
    ["Breaking Needles", [0x0360, 0x0f00, 0x0350, 0x00b0], 4, ""],
    ["DJ AM Presents", [0x12a0, 0x0dd0], 3, "non-bonus "],  
    ["DJ Shadow Presents", [0x0bb0, 0x0c90, 0x01d0], 4, "non-bonus "],
    ["J.Period Presents", [0x01a0, 0x03c0], 2, ""],
    ["DJ Z-Trip Presents", [0x01b0, 0x0110], 2, "non-bonus "],
    ["Tearing up Wax", [0x0260, 0x0210, 0x0240, 0x0e50], 4, ""],
    ["Scratch Perverts Presents", [0x0050, 0x03a0, 0x0090, 0x1090, 0x1170], 5, ""],
    ["The Vinyl Cut", [0x0240, 0x0350, 0x1170, 0x0d60], 1, ""]
]
 
// 5 of those is 0xa0000000, 3 is 0x60000000, 1 is 0x20000000
function mediumStars(baseOffset) => dword_be((dword_be((dword_be(0x797aa8) & 0x1fffffff) + 0xbc) & 0x1fffffff) + baseOffset + 4) & 0xe0000000

// 5 of those is 0xa0, 3 is 0x60, 1 is 0x20
function hardStars(baseOffset) => dword_be((dword_be((dword_be(0x797aa8) & 0x1fffffff) + 0xbc) & 0x1fffffff) + baseOffset + 4) & 0xe0

// 5 of those is 0x14, 3 is 0xc, 1 is 0x4
function expertStars(baseOffset) => dword_be((dword_be((dword_be(0x797aa8) & 0x1fffffff) + 0xbc) & 0x1fffffff) + baseOffset + 4) & 0x1c

function progressionAchievement(offsets){
    prev = always_false()
    mem = always_true()
    combo = always_true()
    for offset in offsets{
        prev = prev || (prev(mediumStars(offset)) < 0x20000000 && mediumStars(offset) >= 0x20000000 || prev(hardStars(offset)) < 0x20 && hardStars(offset) >= 0x20 || prev(expertStars(offset)) < 0x4 && expertStars(offset) >= 0x4)
        mem = mem && (mediumStars(offset) >= 0x20000000 || hardStars(offset) >= 0x20 || expertStars(offset) >= 0x4)
    }
    return isNotCheating() && inGame() && prev && mem 
}

for progression in progressionData{
    achievement(title=progression[0], points=progression[2], type="progression",
                description="Earn at least 1 Star in all " + progression[3] + "Mixes in " + progression[0] + " on Medium difficulty or higher",
                trigger=progressionAchievement(progression[1])
    )
}

function unlockBonusBeat(offset)
{
   return isNotCheating() && inGame() && prev(dword_be((dword_be((dword_be(0x797aa8) & 0x1fffffff) + 0xbc) & 0x1fffffff) + offset)) / 0x80000000 == 0 && dword_be((dword_be((dword_be(0x797aa8) & 0x1fffffff) + 0xbc) & 0x1fffffff) + offset) / 0x80000000 == 1  
}
achievement(title="Mashed in a Flash", points=5,
            description="Unlock the bonus track in Grandmaster Flash Presents",
            trigger=unlockBonusBeat(0x1350)
)

achievement(title="Up for Some Extra Jazz", points=5,
            description="Unlock the bonus track in DJ Jazzy Jeff Presents",
            trigger=unlockBonusBeat(0x0270)
)

achievement(title="Do or Do Not, There Is One More to Try", points=5,
            description="Unlock the bonus track in DJ Jazzy Jeff Presents",
            trigger=unlockBonusBeat(0x02d0)
)

achievement(title="Bottomless Bag", points=5,
            description="Unlock the bonus track in Daft Punk Record Bag",
            trigger=unlockBonusBeat(0x02a0)
)

achievement(title="I AM Ready for More", points=5,
            description="Unlock the bonus track in DJ AM Presents",
            trigger=unlockBonusBeat(0x0310)
)

achievement(title="One More Sonic Treat", points=5,
            description="Unlock the bonus track in DJ Shadow Presents",
            trigger=unlockBonusBeat(0x1420)
)

achievement(title="A Through Z... And Then Some", points=5,
            description="Unlock the bonus track in DJ Shadow Presents",
            trigger=unlockBonusBeat(0x0150)
)

achievement(title="A Final Treat Before You Go", points=3,
            description="Unlock the bonus track in The Vinyl Cut",
            trigger=unlockBonusBeat(0x0250)
)