// Tony Hawk's Downhill Jam
// #ID = 20650

characters = {
    0x0:"Tony",
    0x1:"Kevin",
    0x2:"Kyla",
    0x3:"Gunnar",
    0x4:"Jynx",
    0x5:"Crash",
    0x6:"Armondo",
    0x7:"Ammon",
    0x8:"Budd",
    0x9:"Tiffany",
    0xa:"MacKenzie",
    0xb:"Fang",
    0xc:"Skyler",
    0xd:"Victor",
    0xe:"Custom Character"
}

events = {
    0x01533974: "Elimination, Special, Rome",
    0x06709304: "Swiss Elimination, Special, Alps",
    0x0804e99e: "Dharma Dash, Race, Hong Kong",
    0x093871c9: "Grind Time, Special, Hong Kong",
    0x0acc9ff3: "Seaside Village, Slalom, Rome",
    0x0c0c3bd0: "Knockdown, Special, Rio",
    0x0c119ba7: "Cash Grab, Special, Rome",
    0x0f692d87: "Top to Bottom, Race, Hong Kong",
    0x1059779e: "Top to Bottom, Trick, Hong Kong",
    0x114123ce: "Rome Burning, Race, Rome",
    0x13287523: "Trails of Ruins, Race, Machu Picchu",
    0x13a97bfe: "Cash Grab, Special, San Francisco",
    0x15d1be5b: "Skateboard Mountain, Slalom, Machu Picchu",
    0x162ce7d7: "Fallen Empire, Race, Rome",
    0x1734b387: "Dharma Dash, Trick, Hong Kong",
    0x1756d90f: "Kevin's Challenge, Special, Hong Kong",
    0x182a62bd: "Fallen Empire, Trick, Rome",
    0x1860a303: "Coaster Grind, Special, Chicago",
    0x18640cd4: "Top to Bottom, Trick, Alps",
    0x1a49fe12: "Gunnar's Threads, Race, Edinburgh",
    0x1e4677a0: "Hot Lava, Special, Rio",
    0x1f09c8cd: "Round the Matterhorn, Trick, Alps",
    0x1f47a6a4: "Top To Bottom, Trick, Rome",
    0x204c7506: "Elimination, Special, San Francisco",
    0x22c139bc: "Street Issue, Slalom, Hong Kong",
    0x24447d59: "Out of the Woods, Trick, Rio",
    0x249d7159: "Tourist Trap, Race, San Francisco",
    0x25acfda5: "Top to Bottom, Slalom, Hong Kong",
    0x26accbaf: "Girl Power, Race, Rio",
    0x2a82050c: "Chinatown Tour, Slalom, San Francisco",
    0x2d1e286c: "Boost Jam, Special, Machu Picchu",
    0x2dc9fdf3: "Lift Ticket, Slalom, Alps",
    0x3186c543: "Road to Cuzco, Trick, Machu Picchu",
    0x330f0331: "Top to Bottom, Slalom, Edinburgh",
    0x3399eb76: "Precision Shopping, Slalom, Chicago",
    0x3462c728: "Castle Chaos, Slalom, Edinburgh",
    0x39352ecf: "Twin Peaks, Trick, San Francisco",
    0x3e50f00a: "Clearance Sale, Special, Chicago",
    0x3e58ead6: "Top To Bottom, Trick, San Francisco",
    0x410c33e2: "High Street, Trick, Edinburgh",
    0x454a908a: "Boost Jam, Special, Alps",
    0x4681f5d5: "Skateboard Mountain, Trick, Machu Picchu",
    0x4980e145: "Mall Trash, Trick, Chicago",
    0x4eed255c: "Park It Anywhere, Trick, Chicago",
    0x50da199a: "Bagpipe Beatdown, Special, Edinburgh",
    0x53434dcf: "Favela Rush, Trick, Rio",
    0x539a41cf: "Cable Car Sprint, Race, San Francisco",
    0x572135c4: "Mall Rats, Special, Chicago",
    0x5721eaff: "Chinatown Collision, Special, San Francisco",
    0x57947e95: "Elimination Sale, Special, Chicago",
    0x57c1ce02: "Bully Board, Special, Edinburgh",
    0x5acecd65: "The Hills Are Alive, Slalom, Alps",
    0x5ae8f183: "Twin Peaks, Slalom, San Francisco",
    0x5d85359a: "Top to Bottom, Slalom, San Francisco",
    0x5f2f4aca: "Top to Bottom, Race, Alps",
    0x62af25e2: "Parking Lot Shuffle, Race, Chicago",
    0x62d68ecd: "Road to Cuzco, Slalom, Machu Picchu",
    0x634281ac: "Montain High, Race, Machu Picchu",
    0x642f45b5: "Top To Bottom, Race, Machu Picchu",
    0x68b4e562: "Vista Point, Slalom, Rio",
    0x6d4ece84: "Scottish Catacombs, Race, Edinburgh",
    0x6fd9217b: "Top To Bottom, Slalom, Rio",
    0x762b478f: "Unknown Skater, Special, Alps",
    0x7adb59ab: "Boost Jam, Special, San Francisco",
    0x7bc7a633: "Bully Board, Special, Rio",
    0x7bd7d2f0: "Vista Point, Race, Rio",
    0x7dcbaf65: "Del Centro, Slalom, Rome",
    0x807a206d: "Clear the Streets, Special, Rome",
    0x81233307: "Del Centro, Trick, Rome",
    0x8169f2b9: "Full Mall Grind, Special, Chicago",
    0x8340afa8: "Castle Chaos, Race, Edinburgh",
    0x842d6bb1: "Top to Bottom, Race, Edinburgh",
    0x86009977: "Lift Ticket, Tricks, Alps",
    0x8bb52bf8: "Top to Bottom, Slalom, Machu Picchu",
    0x8ca144ce: "Saturday Matinee, Race, Chicago",
    0x8cd8efe1: "Mountain High, Slalom, Machu Picchu",
    0x8d4ce080: "Road to Cuzco, Race, Machu Picchu",
    0x8f25b66d: "Del Centro, Race, Rome",
    0x95d9b3dc: "Favela Rush, Race, Rio",
    0xad6b9692: "High Street, Slalom, Edinburgh",
    0xb3ad6850: "Top to Bottom, Slalom, Alps",
    0xb4c0ac49: "Round the Matterhorn, Slalom, Alps",
    0xb64cefff: "The Hills Are Alive, Race, Alps",
    0xba20e8fa: "Top to Bottom, Trick, Rio",
    0xbaf9e4fa: "Top to Bottom, Race, San Francisco",
    0xbbc86806: "City Lights, Slalom, Hong Kong",
    0xbd2f466b: "Crash Test, Special, Rio",
    0xbd4d2ce3: "Vista Point, Trick, Rio",
    0xbd9420e3: "Twin Peaks, Race, San Francisco",
    0xc14bdf69: "Lift Off, Race, Alps",
    0xc3e1a039: "Tourist Spot, Slalom, San Francisco",
    0xcccf5890: "Waterfront Wipeout, Slalom, Hong Kong",
    0xd73b4fe3: "Big Air, Trick, San Francisco",
    0xd7e474e6: "Mall Moves, Trick, Chicago",
    0xd8056258: "Castle Chaos, Trick, Edinburgh",
    0xd86708d0: "MacKenzie's Challenge, Special, Edinburgh",
    0xd8e56076: "Top To Bottom, Trick, Machu Picchu",
    0xda6ca604: "Scottish Catacombs, Slalom, Edinburgh",
    0xdaf00296: "Hot Lava, Special, San Francisco",
    0xdf68a641: "Top to Bottom, Trick, Edinburgh",
    0xe2de834a: "Out Of The Woods, Race, Rio",
    0xe3af3ac6: "Top to Bottom, Slalom, Rome",
    0xe4c2fedf: "Fallen Empire, Slalom, Rome",
    0xe60a88b2: "Waterfront Wipeout, Race, Hong Kong",
    0xf107a9e1: "The Hills Are Alive, Trick, Alps",
    0xf1bdb4d8: "Rooftop Tour, Slalom, Rio",
    0xf82286fb: "Seaside Village, Race, Rome",
    0xf93ad2ab: "Waterfront Wipeout, Trick, Hong Kong",
    0xfba67458: "Shopping Spree, Race, Chicago"
}

tiers = {
    0x00: "Greenhorn",
    0x01: "Rookie",
    0x02: "Barnstormer",
    0x03: "Boarder",
    0x04: "Semi-Pro",
    0x05: "Pro",
    0x06: "Champion",
    0x07: "Sensei",
    0x08: "Grandmaster",
    0x09: "Legend",
    0x0a: "Conqueror"
}

boards = {
    0x00: "Basic Board",
    0x01: "Street Issue",
    0x02: "Solar",
    0x03: "Chaos",
    0x04: "Celtic",
    0x05: "Red Rascal",
    0x06: "Cruiser",
    0x07: "Illuminate",
    0x08: "Dark Sign",
    0x09: "Spooky",
    0x0a: "Black Icer",
    0x0b: "Ripper",
    0x0c: "Dispersion",
    0x0d: "Makonga",
    0x0e: "Goddess of Speed",
    0x0f: "Dragon",
    0x10: "Vulture",
    0x11: "Dragon T",
    0x12: "Vanguard"
}

// [EventId, Gate Count]
slalomInfos = [
    [0x22c139bc, 21], // Street Issue, Slalom, Hong Kong
    [0x5ae8f183, 17], // Twin Peaks, Slalom, San Francisco
    [0xcccf5890, 23], // Waterfront Wipeout, Slalom, Hong Kong
    
    [0xbbc86806, 29], // City Lights, Slalom, Hong Kong
    [0xda6ca604, 36], // Scottish Catacombs, Slalom, Edinburgh
    [0xc3e1a039, 26], // Tourist Spot, Slalom, San Francisco
    
    [0x15d1be5b, 15], // Skateboard Mountain, Slalom, Machu Picchu
    [0x68b4e562, 16], // Vista Point, Slalom, Rio
    [0xe4c2fedf, 16], // Fallen Empire, Slalom, Rome
    
    [0xf1bdb4d8, 42], // Rooftop Tour, Slalom, Rio
    [0x8cd8efe1, 10], // Mountain High, Slalom, Machu Picchu
    [0x62d68ecd, 15], // Road to Cuzco, Slalom, Machu Picchu
    
    [0x25acfda5, 54], // Top to Bottom, Slalom, Hong Kong
    [0xad6b9692, 23], // High Street, Slalom, Edinburgh
    [0x2a82050c, 13], // Chinatown Tour, Slalom, San Francisco
    
    [0x3462c728, 22], // Castle Chaos, Slalom, Edinburgh
    [0x3399eb76, 15], // Precision Shopping, Slalom, Chicago
    [0x7dcbaf65, 12], // Del Centro, Slalom, Rome
    
    [0xb4c0ac49, 21], // Round the Matterhorn, Slalom, Alps
    [0x2dc9fdf3, 31], // Lift Ticket, Slalom, Alps
    [0x6fd9217b, 69], // Top To Bottom, Slalom, Rio
    
    [0x5d85359a, 40], // Top to Bottom, Slalom, San Francisco
    [0x0acc9ff3, 16], // Seaside Village, Slalom, Rome
    [0x5acecd65, 37], // The Hills Are Alive, Slalom, Alps
    
    [0xe3af3ac6, 45], // Top to Bottom, Slalom, Rome
    [0x8bb52bf8, 44], // Top to Bottom, Slalom, Machu Picchu
    [0x330f0331, 82], // Top to Bottom, Slalom, Edinburgh
    
    [0xb3ad6850, 87] // Top to Bottom, Slalom, Alps
]

function unlockedBoards(){
    sum = 0
    for index in range(0, 17){
        sum = sum + dword(dword(dword(0x4e4268) + 0x2cac) + 0x188 + 4 * index)
    }
    return 1 + sum
}

function aBoardIsUnlocking(){
    cond = false
    for index in range(0, 17){
        cond = cond || prev(dword(dword(dword(0x4e4268) + 0x2cac) + 0x188 + 4 * index)) == 0 && dword(dword(dword(0x4e4268) + 0x2cac) + 0x188 + 4 * index) == 1
    }
    return cond
}

function unlockedCharacters()
{
    sum = 0
    for index in range(0, 5){
        sum = sum + dword(dword(0x46f90c) + 0x554 + 4 * index)
    }
    return 9 + sum
}

function inRace() => dword(dword(dword(0x4e4268) + 0x1b7c) + 0xc) == 1

rich_presence_conditional_display(dword(0x4adc30) == 0x1, "Playing the \"Behind the Scenes\" Cutscene")

rich_presence_conditional_display(inRace(), "{0} is riding the {1} in {2} - Boards: {3}/19 - Characters: {4}/15 - 👑{5} ({6})", 
                                  rich_presence_lookup("Character", dword(0x4b0678), characters),
                                  rich_presence_lookup("Board", dword(dword(dword(0x4e4268) + 0x184c) + 0x20), boards),
                                  rich_presence_lookup("Event", dword(dword(dword(0x4e4268) + 0x184c) + 0x5c), events),
                                  rich_presence_value("Value", unlockedBoards(), "VALUE"),
                                  rich_presence_value("Value", unlockedCharacters(), "VALUE"),
                                  rich_presence_value("Value", dword(dword(dword(0x4e4268) + 0x2cac) + 0x104), "VALUE"),
                                  rich_presence_lookup("Tier", dword(dword(dword(0x4e4268) + 0x2cac) + 0x134), tiers)
)

rich_presence_conditional_display(dword(dword(dword(0x4a9114) + 0x8510) + 0xc) == 0x5c982102, "Choosing a Skater")

rich_presence_conditional_display(dword(dword(dword(0x4a9114) + 0x8510) + 0xc) == 0x7f2e488f, "In the Events Hub - Boards: {0}/19 - Characters: {1}/15 - 👑{2} ({3})",
                                  rich_presence_value("Value", unlockedBoards(), "VALUE"),
                                  rich_presence_value("Value", unlockedCharacters(), "VALUE"),
                                  rich_presence_value("Value", dword(dword(dword(0x4e4268) + 0x2cac) + 0x104), "VALUE"),
                                  rich_presence_lookup("Tier", dword(dword(dword(0x4e4268) + 0x2cac) + 0x134), tiers)
)

rich_presence_display("Playing Tony Hawk's Downhill Jam")

/**
    Achievements protections:
    1) Using an AntiCheat patch => no cheat protection needed
    2) Save/load protection needs to be done on three fronts:
      - on titles the game fetches a lot of unlock data from the first available savefile (even before actually choosing a savefile to load)
      - if the player switches savefiles in a single session (because data will no be cleared by the game in between)
    For end-of-race achievements, they cannot happen on load anyway, so they are self-protecting
*/
function saveProtection() => dword(dword(dword(0x4a9114) + 0x8510) + 0xc) == 0x7f2e488f //dword(0x4adc7c) == 0 && dword(0x4adc20) == 0xffffffff

achievement("Slightly Better Piece of Wood", id=625004,
            description="Unlock a new board",
            points=1,
            trigger=saveProtection() && aBoardIsUnlocking()
)
            
achievement("What Do You Mean? Of Course I Need 19 Boards!",
            description="Unlock all boards", id=625005,
            points=10,
            trigger=saveProtection() && prev(unlockedBoards()) == 18 && measured(unlockedBoards() == 19)
)   
            
achievement("Easily Done Love! Let Me Know When the Real Competition Starts!",
            description="Unlock MacKenzie", id=625006,
            points=5,
            trigger=saveProtection() && prev(dword(dword(0x46f90c) + 0x554)) == 0 && dword(dword(0x46f90c) + 0x554) == 1 
)   

achievement("It's over Already Huh? I'm Barely Even in Excruciating Pain!",
            description="Unlock Crash", id=625007,
            points=5,
            trigger=saveProtection() && prev(dword(dword(0x46f90c) + 0x558)) == 0 && dword(dword(0x46f90c) + 0x558) == 1
)   

achievement("Now That's How You Skate Downhill... In a Video Game!",
            description="Unlock Kevin", id=625008,
            points=5,
            trigger=saveProtection() && prev(dword(dword(0x46f90c) + 0x55c)) == 0 && dword(dword(0x46f90c) + 0x55c) == 1 
)   

achievement("Winners Are Just Loosers Who Have Lost Their Way!",
            description="Unlock Skyler", id=625009,
            points=5,
            trigger=saveProtection() && prev(dword(dword(0x46f90c) + 0x564)) == 0 && dword(dword(0x46f90c) + 0x564) == 1
)   

achievement("Sometimes You're the Looser and Sometimes You're Me!",
            description="Unlock Victor", id=625010,
            points=5,
            trigger=saveProtection() && prev(dword(dword(0x46f90c) + 0x568)) == 0 && dword(dword(0x46f90c) + 0x568) == 1
)   

outfitOffsets = [
    0x2ec, 0x2f0, 0x2f4, 0x2f8,
    0x318, 0x31c, 0x320, 0x324,
    0x344, 0x348, 0x34c, 0x350,
    0x370, 0x374, 0x378, 0x37c,
    0x39c, 0x3a0, 0x3a4, 0x3a8,
    0x3c8, 0x3cc, 0x3d0, 0x3d4,
    0x3f4, 0x3f8, 0x3fc, 0x400,
    0x420, 0x424, 0x428, 0x42c,
    0x44c, 0x450, 0x454, 0x458,
    0x478, 0x47c, 0x480, 0x484,
    0x4a4, 0x4a8, 0x4ac, 0x4b0,
    0x4d0, 0x4d4, 0x4d8, 0x4dc,
    0x4fc, 0x500, 0x504, 0x508,
    0x528, 0x52c, 0x530, 0x534
]
     
function anOutfitIsUnlocking(){
    cond = false
    for offset in outfitOffsets {
        cond = cond || prev(dword(dword(0x46f90c) + offset)) == 0 && dword(dword(0x46f90c) + offset) == 1
    }
    return cond
}

function fullWardrobeForAChar(){
    cond = false
    for index in range(0, 13){
        charSum = dword(dword(0x46f90c) + outfitOffsets[4 * index]) + dword(dword(0x46f90c) + outfitOffsets[4 * index + 1]) +
                  dword(dword(0x46f90c) + outfitOffsets[4 * index + 2]) + dword(dword(0x46f90c) +  outfitOffsets[4 * index + 3])
        cond = cond || prev(charSum) == 3 && charSum == 4
    }
    return cond
}

function allOutfitsUnlocked(){
    sum = 0
    for offset in outfitOffsets {
        sum = sum + dword(dword(0x46f90c) + offset)
    } 
    return prev(sum) == 55 && measured(sum == 56)
}
     
function didNotCheat() => 0x00 == 0x00
          
function inRaceCountdownMs() => 60000 * dword(dword(dword(0x4e4268) + 0xd3c0) + 0x48) + 1000 * dword(dword(dword(0x4e4268) + 0xd3c0) + 0x5c) + dword(dword(dword(0x4e4268) + 0xd3c0) + 0x70)

function timesUp() => dword(dword(dword(0x4e4268) + 0xd3c0) + 0x48) == 0 && dword(dword(dword(0x4e4268) + 0xd3c0) + 0x5c) == 0 && dword(dword(dword(0x4e4268) + 0xd3c0) + 0x70) == 0
function passedThroughAGate() => prev(dword(dword(dword(0x4e4268) + 0xd3c0) + 0x48)) == dword(dword(dword(0x4e4268) + 0xd3c0) + 0x48) && 
                                 prev(dword(dword(dword(0x4e4268) + 0xd3c0) + 0x5c)) < dword(dword(dword(0x4e4268) + 0xd3c0) + 0x5c) ||
                                 prev(dword(dword(dword(0x4e4268) + 0xd3c0) + 0x48)) < dword(dword(dword(0x4e4268) + 0xd3c0) + 0x48)
          
          
          
achievement("Check These New Threads", id=625011,
            description="Unlock an alternative outfit",
            points=1,
            trigger=saveProtection() && anOutfitIsUnlocking()
)    

/**
achievement("Blinding the Competition with Style",
            description="Wearing an alternative outfit, win gold in any race",
            points=1,
            trigger=dword(dword(0x46f90c) + 0x568) == 1 && prev(dword(dword(0x46f90c) + 0x568)) == 0
) 
*/

achievement("Full Wardrobe", id=625012,
            description="Unlock all alternative outfits for a skater",
            points=5,
            trigger=saveProtection() && fullWardrobeForAChar()
)        

achievement("Fashionista", id=625013,
            description="Unlock all alternative outfits",
            points=10,
            trigger=saveProtection() && allOutfitsUnlocked()
)       

achievement("Rookie", id=625033,
            description="Unlock Tier 2 Events",
            type="progression",
            points=10,
            trigger=saveProtection() && prev(dword(dword(dword(0x4e4268) + 0x2cac) + 0x104)) >= 13 &&
                    prev(dword(dword(dword(0x4e4268) + 0x2cac) + 0x134)) == 0 && dword(dword(dword(0x4e4268) + 0x2cac) + 0x134) == 1 
)     

achievement("Barnstormer", id=625034,
            description="Unlock Tier 3 Events",
            type="progression",
            points=10,
            trigger=saveProtection() && prev(dword(dword(dword(0x4e4268) + 0x2cac) + 0x134)) == 1 && dword(dword(dword(0x4e4268) + 0x2cac) + 0x134) == 2
)  

achievement("Boarder", id=625035,
            description="Unlock Tier 4 Events",
            type="progression",
            points=10,
            trigger=saveProtection()&& prev(dword(dword(dword(0x4e4268) + 0x2cac) + 0x134)) == 2 && dword(dword(dword(0x4e4268) + 0x2cac) + 0x134) == 3
)  

achievement("Semi-Pro", id=625036,
            description="Unlock Tier 5 Events",
            type="progression",
            points=10,
            trigger=saveProtection() && prev(dword(dword(dword(0x4e4268) + 0x2cac) + 0x134)) == 3 && dword(dword(dword(0x4e4268) + 0x2cac) + 0x134) == 4
)     

achievement("Pro", id=625037,
            description="Unlock Tier 6 Events",
            type="progression",
            points=10,
            trigger=saveProtection() && prev(dword(dword(dword(0x4e4268) + 0x2cac) + 0x134)) == 4 && dword(dword(dword(0x4e4268) + 0x2cac) + 0x134) == 5
)     

achievement("Champion", id=625038,
            description="Unlock Tier 7 Events",
            type="progression",
            points=10,
            trigger=saveProtection() && prev(dword(dword(dword(0x4e4268) + 0x2cac) + 0x134)) == 5 && dword(dword(dword(0x4e4268) + 0x2cac) + 0x134) == 6
)     

achievement("Sensei", id=625039,
            description="Unlock Tier 8 Events",
            type="progression",
            points=10,
            trigger=saveProtection() && prev(dword(dword(dword(0x4e4268) + 0x2cac) + 0x134)) == 6 && dword(dword(dword(0x4e4268) + 0x2cac) + 0x134) == 7
)     

achievement("Grandmaster", id=625040,
            description="Unlock Tier 9 Events",
            type="progression",
            points=10,
            trigger=saveProtection() && prev(dword(dword(dword(0x4e4268) + 0x2cac) + 0x134)) == 7 && dword(dword(dword(0x4e4268) + 0x2cac) + 0x134) == 8
)     

achievement("Legend", id=625041,
            description="Unlock Tier 10 Events",
            type="progression",
            points=10,
            trigger=saveProtection() && prev(dword(dword(dword(0x4e4268) + 0x2cac) + 0x134)) == 8 && dword(dword(dword(0x4e4268) + 0x2cac) + 0x134) == 9
)     

achievement("Conqueror", id=625014,
            description="Beat Tier 10 and unlock the Mystery Skater",
            type="win_condition",
            points=25,
            trigger=saveProtection() && dword(dword(0x46f90c) + 0x560) == 1 && prev(dword(dword(0x46f90c) + 0x560)) == 0
)     

achievement("I Could Not Manual So It Took a Bit of Grind", id=625049,
            description="Reach 100% with any character",
            points=25,
            trigger=saveProtection() && 
                    prev(dword(dword(dword(0x4e4268) + 0x2cac) + 0x104)) < 827 && 
                    prev(dword(dword(dword(0x4e4268) + 0x2cac) + 0x104)) >= 815 && 
                    dword(dword(dword(0x4e4268) + 0x2cac) + 0x104) == 827
)

// THIS IS WRONG!!!
function raceOver() => inRace() && prev(float(0x5e523c)) != float(0x5e523c)
function raceOverTrigger() => inRace() && trigger_when(prev(float(0x5e523c)) != float(0x5e523c))

achievement("A Cool Mil",
            description="Finish any Event with a raw Score statistic of at least 1,000,000",
            points=10,
            trigger=dword(0x5df134) >= 1000000 && raceOver()
)

achievement("Isn't the Point to Show Off?",
            description="Finish any Event with a Longest Combo Length statistic of at least 1 minute",
            points=10,
            trigger=float(0x5e242c) >= 60.0 && raceOver()
)

achievement("I'm Not Here for the View", id=624200,
            description="Finish any Event with a Percent of Time at Max Speed statistic of at least 80%",
            points=5,
            trigger=float(0x5e2578) / float(0x5e523c) >= 0.8 && raceOver()
)

achievement("Were We Allowed to Touch the Ground?",
            description="Finish any Event with a Percent of Time on Ground statistic of at most 20%",
            points=5,
            trigger=float(0x5e25d4) / float(0x5e523c) <= 0.2 && raceOver()
)

achievement("Winning with Style",
            description="Finish any Event with a Total Tricks statistic of at least 300",
            points=5,
            trigger=dword(0x5df1d8) + dword(0x5df1dc) >= 300 && raceOver()
)


function boostJam() => dword(dword(dword(0x4e4268) + 0x184c) + 0x5c) == 0x454a908a ||
                       dword(dword(dword(0x4e4268) + 0x184c) + 0x5c) == 0x2d1e286c ||
                       dword(dword(dword(0x4e4268) + 0x184c) + 0x5c) == 0x7adb59ab

achievement("Getting a Hang on Those Speed Boosts", id=626452,
            description="Finish any Event except a Boost Jam with a Speed Boost Chained statistic of at least 5",
            points=5,
            trigger= !boostJam() && dword(0x5e24c8) >= 5 && raceOver()
)

achievement("Wheels on Fire", id=626453,
            description="Finish any Event except a Boost Jam with a Speed Boost Chained statistic of at least 10",
            points=10,
            trigger= !boostJam() && dword(0x5e24c8) >= 10 && raceOver()
)


function allGatesInASlalom()
{
    cond = false
    for slalomInfo in slalomInfos
    {
        cond = cond || dword(dword(dword(0x4e4268) + 0x184c) + 0x5c) == slalomInfo[0] && tally(slalomInfo[1], passedThroughAGate())
    }    
    return cond
}

achievement("Time Collector", id=625528,
            description="In any Slalom Event, pass through all Gates and finish the Event",
            points=5,
            trigger=raceOver() && never(prev(timesUp())) && allGatesInASlalom()
)

achievement("Porta Maggiore", id=625555,
            description="In the Top to Bottom Slalom Event in Rome, pass through all 45 Gates and finish the Event",
            points=10,
            trigger=raceOverTrigger() && never(prev(timesUp())) && dword(dword(dword(0x4e4268) + 0x184c) + 0x5c) == 0xe3af3ac6 &&
                    trigger_when(tally(45, passedThroughAGate()))
)

achievement("Intipunku", id=625556,
            description="In the Top to Bottom Slalom Event in Machu Picchu, pass through all 44 Gates and finish the Event",
            points=10,
            trigger=raceOverTrigger() && never(prev(timesUp())) && dword(dword(dword(0x4e4268) + 0x184c) + 0x5c) == 0x8bb52bf8 &&
                    trigger_when(tally(44, passedThroughAGate()))
)

achievement("Dragon Holes", id=625557,
            description="In the Top to Bottom Slalom Event in Hong Kong, pass through all 54 Gates and finish the Event",
            points=10,
            trigger=raceOverTrigger() && never(prev(timesUp())) && dword(dword(dword(0x4e4268) + 0x184c) + 0x5c) == 0x25acfda5 &&
                    trigger_when(tally(54, passedThroughAGate()))
)

achievement("The Canongate", id=625558,
            description="In the Top to Bottom Slalom Event in Edinburgh, pass through all 82 Gates and finish the Event",
            points=10,
            trigger=raceOverTrigger() && never(prev(timesUp())) && dword(dword(dword(0x4e4268) + 0x184c) + 0x5c) == 0x330f0331 &&
                    trigger_when(tally(82, passedThroughAGate()))
)

achievement("Gate of Heaven", id=625559,
            description="In the Top to Bottom Slalom Event in Rio, pass through all 69 Gates and finish the Event",
            points=10,
            trigger=raceOverTrigger() && never(prev(timesUp())) && dword(dword(dword(0x4e4268) + 0x184c) + 0x5c) == 0x6fd9217b &&
                    trigger_when(tally(69, passedThroughAGate()))
)

achievement("Golden Gate", id=625560,
            description="In the Top to Bottom Slalom Event in San Francisco, pass through all 40 Gates and finish the Event",
            points=10,
            trigger=raceOverTrigger() && never(prev(timesUp())) && dword(dword(dword(0x4e4268) + 0x184c) + 0x5c) == 0x5d85359a &&                    
                    trigger_when(tally(40, passedThroughAGate()))
)

achievement("Portes du Soleil", id=625561,
            description="In the Top to Bottom Slalom Event in the Alps, pass through all 87 Gates and finish the Event",
            points=10,
            trigger=raceOverTrigger() && never(prev(timesUp())) && dword(dword(dword(0x4e4268) + 0x184c) + 0x5c) == 0xb3ad6850 &&
                    trigger_when(tally(87, passedThroughAGate()))
)

achievement("Gold Is Not Enough", id=625579,
            description="Beat any Event's record and be rewarded with a Golden Crown with Diamonds or better",
            points=5,
            trigger=inRace() && once(prev(float(0x5e523c)) != float(0x5e523c)) && never(!inRace()) && 
                    prev(dword(dword(dword(0x4e4268) + 0x184c) + 0x84)) < 4 && dword(dword(dword(0x4e4268) + 0x184c) + 0x84) >= 4
)
            
achievement("Crown Jewels", id=625580,
            description="Beat any Event's record and be rewarded with a Golden Crown with Diamonds and Rubies",
            points=10,
            trigger=inRace() && once(prev(float(0x5e523c)) != float(0x5e523c)) && never(!inRace()) && 
                    prev(dword(dword(dword(0x4e4268) + 0x184c) + 0x84)) < 5 && dword(dword(dword(0x4e4268) + 0x184c) + 0x84) == 5
)

trickEventIds = [0x182a62bd, 0xf93ad2ab, 0x86009977, 0x4681f5d5, 0xdf68a641, 0x81233307, 0xf107a9e1, 0x24447d59, 0x1f09c8cd, 0x1f47a6a4,
                 0x53434dcf, 0x4980e145, 0x39352ecf, 0xbd4d2ce3, 0x1734b387, 0xd7e474e6, 0xd8056258, 0x3186c543, 0x3e58ead6, 0x18640cd4, 
                 0x4eed255c, 0x410c33e2, 0xd73b4fe3, 0x1059779e, 0xba20e8fa, 0xd8e56076]
                 
function anyTrickEvent()
{
    cond = false
    for trickEventId in trickEventIds
    {
        cond = cond || dword(dword(dword(0x4e4268) + 0x184c) + 0x5c) == trickEventId
    }    
    return cond
}                 

function skateLettersPicked() => dword(dword(dword(0x4a9114) + 0x5988) + 0xc) == 5
achievement("Arcade Mode", id=625804,
            description="In any Trick Event, collect SKATE and finish the Event",
            points=5,
            trigger=skateLettersPicked() && anyTrickEvent() && raceOver() 
)

achievement("Too Bad This Game Does Not Have the Pizza Guy",
            description="Collect SKATE and then win the Top to Bottom Trick Event in Rome",
            points=10,
            trigger=dword(dword(dword(0x4e4268) + 0x184c) + 0x5c) == 0x1f47a6a4 && skateLettersPicked() && raceOver()
)

achievement("Inca-redible Skating",
            description="Collect SKATE and then win the Top to Bottom Trick Event in Machu Picchu",
            points=10,
            trigger=dword(dword(dword(0x4e4268) + 0x184c) + 0x5c) == 0xd8e56076 && skateLettersPicked() && raceOver()
)

achievement("Spring Roll",
            description="Collect SKATE and then win the Top to Bottom Trick Event in Hong Kong",
            points=10,
            trigger=dword(dword(dword(0x4e4268) + 0x184c) + 0x5c) == 0x1059779e && skateLettersPicked() && raceOver()
)

achievement("Haggis and Hardflips",
            description="Collect SKATE and then win the Top to Bottom Trick Event in Edinburgh",
            points=10,
            trigger=dword(dword(dword(0x4e4268) + 0x184c) + 0x5c) == 0xdf68a641 && skateLettersPicked() && raceOver()
)

achievement("Carnival of Kickflips",
            description="Collect SKATE and then win the Top to Bottom Trick Event in Rio",
            points=10,
            trigger=dword(dword(dword(0x4e4268) + 0x184c) + 0x5c) == 0xba20e8fa && skateLettersPicked() && raceOver()
)

achievement("California Roll",
            description="Collect SKATE and then win the Top to Bottom Trick Event in San Francisco",
            points=10,
            trigger=dword(dword(dword(0x4e4268) + 0x184c) + 0x5c) == 0x3e58ead6 && skateLettersPicked() && raceOver()
)

achievement("Skating Is Just Snowboarding with Wheels",
            description="Collect SKATE and then win the Top to Bottom Trick Event in the Alps",
            points=10,
            trigger=dword(dword(dword(0x4e4268) + 0x184c) + 0x5c) == 0x18640cd4 && skateLettersPicked() && raceOver()
)

function totalSecondsEquals(targetSeconds) => 60 * dword(dword(dword(0x4e4268) + 0xd3c0) + 0x48) + dword(dword(dword(0x4e4268) + 0xd3c0) + 0x5c)  == targetSeconds && dword(dword(dword(0x4e4268) + 0xd3c0) + 0x70) == 0

achievement("The Best Way Not to Be Last Is to Be First", 
            description="Win any Elimination Event while being first each time someone gets eliminated",
            points=5,
            trigger=raceOver() && (dword(dword(dword(0x4e4268) + 0x184c) + 0x5c) == 0x204c7506 || dword(dword(dword(0x4e4268) + 0x184c) + 0x5c) == 0x57947e95 ||
                                   dword(dword(dword(0x4e4268) + 0x184c) + 0x5c) == 0x01533974 || dword(dword(dword(0x4e4268) + 0x184c) + 0x5c) == 0x06709304) &&
                    once(dword(dword(dword(0x4a9114) + 0x7514) + 0xc) == 0 && totalSecondsEquals(dword(dword(dword(0x4e427c) + 0x3e10) + 0xc))) && 
                    once(dword(dword(dword(0x4a9114) + 0x7514) + 0xc) == 0 && totalSecondsEquals(2 * dword(dword(dword(0x4e427c) + 0x3e10) + 0xc))) && 
                    once(dword(dword(dword(0x4a9114) + 0x7514) + 0xc) == 0 && totalSecondsEquals(3 * dword(dword(dword(0x4e427c) + 0x3e10) + 0xc))) && 
                    once(dword(dword(dword(0x4a9114) + 0x7514) + 0xc) == 0 && totalSecondsEquals(4 * dword(dword(dword(0x4e427c) + 0x3e10) + 0xc)))
)

achievement("Slow and Steady Wins the Race", 
            description="Win any Elimination Event while being next to last each time someone gets eliminated",
            points=5,
            trigger=raceOver() && (dword(dword(dword(0x4e4268) + 0x184c) + 0x5c) == 0x204c7506 || dword(dword(dword(0x4e4268) + 0x184c) + 0x5c) == 0x57947e95 ||
                                   dword(dword(dword(0x4e4268) + 0x184c) + 0x5c) == 0x01533974 || dword(dword(dword(0x4e4268) + 0x184c) + 0x5c) == 0x06709304) &&
                    once(dword(dword(dword(0x4a9114) + 0x7514) + 0xc) == 3 && totalSecondsEquals(dword(dword(dword(0x4e427c) + 0x3e10) + 0xc))) && 
                    once(dword(dword(dword(0x4a9114) + 0x7514) + 0xc) == 2 && totalSecondsEquals(2 * dword(dword(dword(0x4e427c) + 0x3e10) + 0xc))) && 
                    once(dword(dword(dword(0x4a9114) + 0x7514) + 0xc) == 1 && totalSecondsEquals(3 * dword(dword(dword(0x4e427c) + 0x3e10) + 0xc))) && 
                    once(dword(dword(dword(0x4a9114) + 0x7514) + 0xc) == 0 && totalSecondsEquals(4 * dword(dword(dword(0x4e427c) + 0x3e10) + 0xc)))
)